local Commanders = {
	["corcom"] = true,
	["corcom1"] = true,
	["corcom3"] = true,
	["corcom5"] = true,
	["corcom6"] = true,
	["corcom7"] = true,
	["armcom"] = true,
	["armcom1"] = true,
	["armcom4"] = true,
	["armcom5"] = true,
	["armcom6"] = true,
	["armcom7"] = true,
	["tllcom"] = true,
	["tllcom3"] = true,
	["tllcom5"] = true,
	["tllcom6"] = true,
	["tllcom7"] = true,
}

local sortedBuildlist = {
	"aach",
	"aafus",
	"aahp",
	"aahpns",
	"abroadside",
	"abuilderlvl1",
	"abuilderlvl2",
	"abuilderlvl3",
	"acovertopscentre",
	"aexxec",
	"afusionplant",
	"ahermes",
	"airwolf3g",
	"ajuno",
	"akmech",
	"ametalmakerlvl1",
	"ametalmakerlvl2",
	"amgeo",
	"amortor",
	"ananotower",
	"anvil",
	"apache",
	"apocketfusion",
	"arm_big_bertha",
	"arm_furie",
	"arm_guardian",
	"arm_immolator",
	"arm_wind_generator",
	"armaak",
	"armaap",
	"armaas",
	"armaaspd",
	"armaca",
	"armack",
	"armacsub",
	"armacv",
	"armadvsol",
	"armah",
	"armah256",
	"armalab",
	"armamaker",
	"armamb",
	"armamd",
	"armamd1",
	"armamd2",
	"armamex",
	"armamph",
	"armamspd",
	"armanac",
	"armanni",
	"armanni1",
	"armantar",
	"armap",
	"armarad",
	"armarch",
	"armarty",
	"armaser",
	"armason",
	"armasp",
	"armasy",
	"armatidal",
	"armatl",
	"armatlas",
	"armavp",
	"armawac",
	"armawin",
	"armbanth",
	"armbanth1",
	"armbats",
	"armbc",
	"armbeaver",
	"armblab",
	"armblz",
	"armbrawl",
	"armbrtha",
	"armbrtha1",
	"armbull",
	"armbull2",
	"armca",
	"armcarry",
	"armcav",
	"armcbomb",
	"armcd",
	"armch",
	"armciph",
	"armcir",
	"armcir1",
	"armck",
	"armckfus",
	"armckmakr",
	"armclaw",
	"armcom",
	"armcom1",
	"armcom4",
	"armcom5",
	"armcom6",
	"armcom7",
	"armcp",
	"armcrabe",
	"armcroc",
	"armcrus",
	"armcs",
	"armcsa",
	"armcspid",
	"armcv",
	"armcybr",
	"armcyclone",
	"armdark",
	"armdf",
	"armdfly",
	"armdl",
	"armdrag",
	"armdragf",
	"armeap",
	"armeman",
	"armemp",
	"armestor",
	"armesy",
	"armevp",
	"armeyes",
	"armfark",
	"armfark1",
	"armfast",
	"armfatf",
	"armfav",
	"armfboy",
	"armfboy1",
	"armfdrag",
	"armfflak",
	"armfhlt",
	"armfhp",
	"armfido",
	"armfig",
	"armflak",
	"armflash",
	"armflash1",
	"armflea",
	"armflea1",
	"armflosh",
	"armflspd",
	"armfmine3",
	"armfmkr",
	"armfor",
	"armfort",
	"armfrad",
	"armfrt",
	"armfsilo",
	"armfus",
	"armgate",
	"armgate1",
	"armgate2",
	"armgen",
	"armgeo",
	"armgmm",
	"armgor",
	"armguard",
	"armham",
	"armham1",
	"armhawk",
	"armhcar",
	"armhdpw",
	"armhevsenan",
	"armhh",
	"armhls",
	"armhlt",
	"armhp",
	"armhplasma",
	"armhys",
	"armiguana",
	"armjade",
	"armjag",
	"armjam",
	"armjamt",
	"armjanus",
	"armjanus1",
	"armjaspd",
	"armjeth",
	"armjugg",
	"armkam",
	"armkrmi",
	"armlab",
	"armlance",
	"armlashover",
	"armlaspd",
	"armlatnk",
	"armlightfus",
	"armllt",
	"armllt1",
	"armmagneto",
	"armmakr",
	"armmanni",
	"armmark",
	"armmart",
	"armmarv",
	"armmas",
	"armmav",
	"armmcv",
	"armmech",
	"armmedt",
	"armmerl",
	"armmex",
	"armmex1",
	"armmh",
	"armmine1",
	"armmine2",
	"armmine3",
	"armmlrs",
	"armmls",
	"armmlspd",
	"armmlv",
	"armmmkr",
	"armmoho",
	"armmship",
	"armmstor",
	"armnanotc",
	"armnanotc1",
	"armnanotc2",
	"armnanotc3",
	"armor",
	"armorca",
	"armorco",
	"armorion",
	"armpaspd",
	"armpb",
	"armpeep",
	"armpers",
	"armpincer",
	"armplat",
	"armpnix",
	"armpod",
	"armpraet",
	"armpt",
	"armpw",
	"armpw1",
	"armrad",
	"armrad1",
	"armraptor",
	"armraven",
	"armraven1",
	"armraz",
	"armraz1",
	"armrech18",
	"armrech21",
	"armrech3",
	"armrecl",
	"armrectr",
	"armrezspd",
	"armrl",
	"armrl1",
	"armrock",
	"armrock1",
	"armroy",
	"armsaber",
	"armsam",
	"armsam1",
	"armsb",
	"armscab",
	"armscab1",
	"armscar",
	"armscpion",
	"armsd",
	"armseap",
	"armseer",
	"armsehak",
	"armsfig",
	"armsh",
	"armsh175",
	"armshltx",
	"armshltx1",
	"armshock",
	"armshock1",
	"armsiege",
	"armsilo",
	"armsilo1",
	"armsjam",
	"armsl",
	"armsnipe",
	"armsolar",
	"armsonar",
	"armsonic",
	"armspid",
	"armsptk",
	"armspy",
	"armst",
	"armstump",
	"armstump1",
	"armsub",
	"armsubk",
	"armsy",
	"armt4store",
	"armtabi",
	"armtarg",
	"armtem",
	"armthovr",
	"armthund",
	"armtick",
	"armtide",
	"armtigre2",
	"armtl",
	"armtrmph",
	"armtship",
	"armtspd",
	"armtys",
	"armuwadves",
	"armuwadvms",
	"armuwes",
	"armuwfus",
	"armuwfus1",
	"armuwlightfus",
	"armuwmex",
	"armuwmme",
	"armuwmmm",
	"armuwms",
	"armvader",
	"armveil",
	"armvhlt",
	"armvisit",
	"armvp",
	"armvulc",
	"armvulc1",
	"armvulc2",
	"armwar",
	"armwin",
	"armyork",
	"armzeus",
	"armzeus1",
	"aseadragon",
	"ashipyardlvl3",
	"aspdbunk",
	"asubpen",
	"avtr",
	"blackdawn",
	"blade",
	"bladew",
	"blotter",
	"cach",
	"cadvmsto",
	"cafus",
	"cahp",
	"cahpns",
	"cbrutus",
	"cbuilderlvl1",
	"cbuilderlvl2",
	"cbuilderlvl3",
	"ccovertopscentre",
	"cdevastator",
	"cfusionplant",
	"champ",
	"chopper",
	"cjuno",
	"clb",
	"cmetalmakerlvl1",
	"cmetalmakerlvl2",
	"cmgeo",
	"cmortor",
	"cnanotower",
	"commando",
	"concealer",
	"consul",
	"consul1",
	"coraak",
	"coraap",
	"coraca",
	"corack",
	"coracsub",
	"coracv",
	"coradon",
	"coradvsol",
	"corah",
	"corak",
	"corak1",
	"coralab",
	"coramaker",
	"coramph",
	"corap",
	"corape",
	"corarad",
	"corarch",
	"corason",
	"corasp",
	"corasship",
	"corassis",
	"corasy",
	"coratidal",
	"coratl",
	"coravp",
	"corawac",
	"corawin",
	"corbats",
	"corbhmth",
	"corbhmth1",
	"corblackhy",
	"corboucher",
	"corbt",
	"corbtrans",
	"corbuzz",
	"corbuzz1",
	"corbuzz2",
	"corca",
	"corcan",
	"corcarry",
	"corch",
	"corck",
	"corcom",
	"corcom1",
	"corcom3",
	"corcom5",
	"corcom6",
	"corcom7",
	"corcrab",
	"corcrash",
	"corcrus",
	"corcrw",
	"corcs",
	"corcsa",
	"corcut",
	"corcv",
	"cordem",
	"cordl",
	"cordoom",
	"cordoom1",
	"cordrag",
	"cordrag1",
	"core_immolator",
	"core_intimidator",
	"core_wind_generator",
	"coreap",
	"corech18",
	"corech21",
	"corech3",
	"coreclipse",
	"coredauber",
	"corehpad",
	"corekaty",
	"coremech",
	"corenaa",
	"corerad",
	"corerad1",
	"corerex",
	"corestor",
	"coresupp",
	"coresy",
	"coreter",
	"corevp",
	"corexp",
	"coreyes",
	"corfalc",
	"corfast",
	"corfast1",
	"corfatf",
	"corfav",
	"corfdrag",
	"corfhlt",
	"corfhp",
	"corfink",
	"corflak",
	"corflshd",
	"corflu",
	"corfmd",
	"corfmd1",
	"corfmd2",
	"corfmine3",
	"corfmkr",
	"corfort",
	"corfrad",
	"corfred",
	"corfrog",
	"corfrt",
	"corfsilo",
	"corfus",
	"corgala",
	"corgant",
	"corgant1",
	"corgarp",
	"corgate",
	"corgate1",
	"corgate2",
	"corgator",
	"corgator1",
	"corgen",
	"corgeo",
	"corgfbt",
	"corgol",
	"corgol1",
	"corgripn",
	"corhcar",
	"corhelo",
	"corhevsenan",
	"corhlt",
	"corhmakr",
	"corhover3g",
	"corhp",
	"corhrk",
	"corhunt",
	"corhurc",
	"corint",
	"corint1",
	"corjamt",
	"corjeag",
	"corjurgen",
	"corkarg",
	"corkarg1",
	"corkrog",
	"corkrog1",
	"corlab",
	"corlevlr",
	"corlevlr1",
	"corlightfus",
	"corllt",
	"corllt1",
	"cormabm",
	"cormabm1",
	"cormachn",
	"cormakr",
	"cormart",
	"cormas",
	"cormatch",
	"cormaw",
	"cormddm",
	"cormena",
	"cormex",
	"cormex1",
	"cormexp",
	"cormh",
	"cormine1",
	"cormine2",
	"cormine3",
	"cormist",
	"cormist1",
	"cormls",
	"cormlv",
	"cormmkr",
	"cormoho",
	"cormonsta",
	"cormort",
	"cormship",
	"cormstor",
	"cormuskrat",
	"cornanotc",
	"cornanotc1",
	"cornanotc2",
	"cornanotc3",
	"cornecro",
	"corparrow",
	"corplat",
	"corpre",
	"corprot",
	"corpt",
	"corpun",
	"corpyro",
	"corpyrox",
	"corrad",
	"corrad1",
	"corrag",
	"corraid",
	"corraid1",
	"correap",
	"correcl",
	"corrl",
	"corrl1",
	"corroach",
	"corroy",
	"corsb",
	"corsbomb",
	"corsd",
	"corseal",
	"corseap",
	"corsent",
	"corsfig",
	"corsfus",
	"corsh",
	"corshad",
	"corshark",
	"corshroud",
	"corsilo",
	"corsilo1",
	"corsjam",
	"corsktl",
	"corsnap",
	"corsolar",
	"corsonar",
	"corspec",
	"corspy",
	"corssub",
	"corstorm",
	"corstorm1",
	"corsub",
	"corsumo",
	"corsumo1",
	"corsy",
	"cortarg",
	"cortermite",
	"corthovr",
	"corthud",
	"corthud1",
	"cortide",
	"cortitan",
	"cortl",
	"cortoast",
	"cortotal",
	"cortron",
	"cortship",
	"cortyrnt",
	"corupmex",
	"coruwadves",
	"coruwadvms",
	"coruwes",
	"coruwfus",
	"coruwlightfus",
	"coruwmex",
	"coruwmme",
	"coruwmmm",
	"coruwms",
	"corvalk",
	"corvamp",
	"corveng",
	"corvhlt",
	"corvipe",
	"corvoyr",
	"corvp",
	"corvrad",
	"corvroc",
	"corwin",
	"corwolv",
	"corwolv1",
	"cpocketfusion",
	"crnns",
	"cshipyardlvl4",
	"cslicer",
	"csubpen",
	"dao",
	"decade",
	"devastator",
	"ferret",
	"gladiator",
	"gorg",
	"heavyimpact",
	"helepolis",
	"hllt",
	"hyperion",
	"intruder",
	"krogtaar",
	"macross",
	"madsam",
	"marauder",
	"mercury",
	"monkeylord",
	"nebraska",
	"nsaagriz",
	"nsaatorph",
	"nsacanglr",
	"nsacbehe",
	"nsaclash",
	"nsacskv",
	"packo",
	"r75-v",
	"requ1",
	"rockblack",
	"screamer",
	"shiva",
	"shrike",
	"smasher",
	"speeder",
	"spiderlab",
	"taipan",
	"tankanotor",
	"tawf001",
	"tawf009",
	"tawf010",
	"tawf013",
	"tawf0131",
	"tawf014",
	"tawf015",
	"tawf114",
	"tawf116",
	"tllaak",
	"tllaap",
	"tllabomber",
	"tllaca",
	"tllacid",
	"tllack",
	"tllacs",
	"tllacsub",
	"tllacv",
	"tlladt",
	"tlladvfight",
	"tlladvsolar",
	"tllalab",
	"tllambassador",
	"tllamex",
	"tllammaker",
	"tllamphibot",
	"tllannouncer",
	"tllantinuke",
	"tllap",
	"tllarad",
	"tllarchnano",
	"tllares",
	"tllariman",
	"tllartybot",
	"tllasonar",
	"tllasp",
	"tllaspns",
	"tllasship",
	"tllasy",
	"tllatidal",
	"tllatorp",
	"tllauwmex",
	"tllavp",
	"tllbats2",
	"tllbind",
	"tllblind",
	"tllboat2",
	"tllbomber",
	"tllbug",
	"tllburner",
	"tllca",
	"tllchover",
	"tllck",
	"tllcoldfus",
	"tllcom",
	"tllcom3",
	"tllcom5",
	"tllcom6",
	"tllcom7",
	"tllconfuser",
	"tllconvincer",
	"tllcop1",
	"tllcopter",
	"tllcoyote",
	"tllcrawlb",
	"tllcs",
	"tllcsa",
	"tllcsub",
	"tllcv",
	"tlldb",
	"tlldcsta",
	"tlldemon",
	"tlldivine",
	"tlldt",
	"tlldtns",
	"tllemp",
	"tllemstor",
	"tllequalizer",
	"tllestor",
	"tllevp",
	"tllfight",
	"tllfireraiser",
	"tllfirestarter",
	"tllflak",
	"tllgate",
	"tllgate1",
	"tllgeo",
	"tllgiant",
	"tllgladius",
	"tllgrim",
	"tllhevsenan",
	"tllhlt",
	"tllhltns",
	"tllhmt",
	"tllhoplit",
	"tllhovergauss",
	"tllhoverlight",
	"tllhovermissile",
	"tllhoverrocket",
	"tllhp",
	"tllhplasma",
	"tllhpns",
	"tllhrk",
	"tllhtcb",
	"tllhtcp",
	"tllhtml",
	"tllion",
	"tlljam",
	"tlllab",
	"tlllasbot",
	"tlllbt",
	"tlllft",
	"tlllmt",
	"tlllmtns",
	"tllloki",
	"tlllongshot",
	"tlllrpt",
	"tllmanta",
	"tllmedfusion",
	"tllmegacoldfus",
	"tllmex",
	"tllmixer",
	"tllmlrpc",
	"tllmm",
	"tllmohogeo",
	"tllmono",
	"tllmstor",
	"tllnanotc",
	"tllnanotc1",
	"tllnanotc2",
	"tllnssam",
	"tllobliterator",
	"tllobscurer",
	"tllobserver",
	"tllorc",
	"tllotter",
	"tllpbot",
	"tllplasma",
	"tllplat",
	"tllplunger",
	"tllprivate",
	"tllprob",
	"tllpulaser",
	"tllpuncher",
	"tllradar",
	"tllrichter",
	"tllriot",
	"tllrlrpc",
	"tllroaster",
	"tllrobber",
	"tllrsplane",
	"tllsalamander",
	"tllsam",
	"tllseab",
	"tllseaf",
	"tllsealock",
	"tllsham",
	"tllshark",
	"tllshoretorp",
	"tllsilo",
	"tllsniper",
	"tllsolar",
	"tllsolarns",
	"tllsonar",
	"tllsonpl",
	"tllsquid",
	"tllsting",
	"tllstuner",
	"tllsubpen",
	"tllsy",
	"tlltarg",
	"tlltelsatnk",
	"tllthumper",
	"tlltide",
	"tlltorp",
	"tlltorpcop",
	"tlltorpp",
	"tlltower",
	"tlltplane",
	"tlltraq",
	"tllturtle",
	"tllupgweb",
	"tlluwestorage",
	"tlluwfusion",
	"tlluwjam",
	"tlluwmex",
	"tlluwmstorage",
	"tllvaliant",
	"tllviking",
	"tllviolator",
	"tllvisitor",
	"tllvp",
	"tllweb",
	"tllwhale",
	"tllwindtrap",
	"tllwmconv",
	"trem",
	"troman",
	"uppercut",
	"vaporiser",
	"watcher"
}

local sortedBuildlistInverted = {}
for f=1, #sortedBuildlist do
	sortedBuildlistInverted[sortedBuildlist[f]] = f
end

local WTimeUnits = {
	arm = {
		["armaap"] = true,
		["armaca"] = true,
		["armack"] = true,
		["armacsub"] = true,
		["armacv"] = true,
		["armalab"] = true,
		["armap"] = true,
		["armasp"] = true,
		["armasy"] = true,
		["armavp"] = true,
		["armbeaver"] = true,
		["armblab"] = true,
		["armca"] = true,
		["armcarry"] = true,
		["armch"] = true,
		["armck"] = true,
		["armcom"] = true,
		["armcom1"] = true,
		["armcom4"] = true,
		["armcom5"] = true,
		["armcom6"] = true,
		["armcom7"] = true,
		["armcp"] = true,
		["armcs"] = true,
		["armcsa"] = true,
		["armcspid"] = true,
		["armcv"] = true,
		["armesy"] = true,
		["armevp"] = true,
		["armfark"] = true,
		["armfark1"] = true,
		["armfhp"] = true,
		["armgant"] = true,
		["armhcar"] = true,
		["armhevsenan"] = true,
		["armhp"] = true,
		["armlab"] = true,
		["armmechl"] = true,
		["armmls"] = true,
		["armmlspd"] = true,
		["armmlv"] = true,
		["armnanotc"] = true,
		["armnanotc1"] = true,
		["armnanotc2"] = true,
		["armnanotc3"] = true,
		["armplat"] = true,
		["armrecl"] = true,
		["armrectr"] = true,
		["armrezspd"] = true,
		["armshltx"] = true,
		["armshltx1"] = true,
		["armsy"] = true,
		["armtick"] = true,
		["armvp"] = true,
		["aahp"] = true,
		["aahpns"] = true,
		["aach"] = true,
		["abuilderlvl1"] = true,
		["abuilderlvl2"] = true,
		["abuilderlvl3"] = true,
		["acovertopscentre"] = true,
		["ananotower"] = true,
		["ashipyardlvl3"] = true,
		["asubpen"] = true,
		["consul1"] = true,
		["spiderlab"] = true,
	},
	core = {
		["coraap"] = true,
		["coraca"] = true,
		["corack"] = true,
		["coracsub"] = true,
		["coracv"] = true,
		["coralab"] = true,
		["corap"] = true,
		["corasp"] = true,
		["corasy"] = true,
		["coravp"] = true,
		["corca"] = true,
		["corcarry"] = true,
		["corch"] = true,
		["corck"] = true,
		["corcom"] = true,
		["corcom1"] = true,
		["corcom3"] = true,
		["corcom5"] = true,
		["corcom6"] = true,
		["corcom7"] = true,
		["corcs"] = true,
		["corcsa"] = true,
		["corcv"] = true,
		["corehpad"] = true,
		["coresy"] = true,
		["corevp"] = true,
		["corfast"] = true,
		["corfast1"] = true,
		["corfhp"] = true,
		["corgant"] = true,
		["corgant1"] = true,
		["corhcar"] = true,
		["corhevsenan"] = true,
		["corhp"] = true,
		["corjurgen"] = true,
		["corlab"] = true,
		["cormls"] = true,
		["cormlv"] = true,
		["cormuskrat"] = true,
		["cornanotc"] = true,
		["cornanotc1"] = true,
		["cornanotc2"] = true,
		["cornanotc3"] = true,
		["cornecro"] = true,
		["corplat"] = true,
		["correcl"] = true,
		["corsy"] = true,
		["cortl"] = true,
		["corvp"] = true,
		["cahp"] = true,
		["cahpns"] = true,
		["cach"] = true,
		["cbuilderlvl1"] = true,
		["cbuilderlvl2"] = true,
		["cbuilderlvl3"] = true,
		["ccovertopscentre"] = true,
		["cnanotower"] = true,
		["commando"] = true,
		["consul"] = true,
		["cshipyardlvl4"] = true,
		["csubpen"] = true,
	},
	tll = {
		["tllaap"] = true,
		["tllaca"] = true,
		["tllack"] = true,
		["tllacs"] = true,
		["tllacsub"] = true,
		["tllacv"] = true,
		["tllalab"] = true,
		["tllap"] = true,
		["tllarchnano"] = true,
		["tllasp"] = true,
		["tllaspns"] = true,
		["tllasy"] = true,
		["tllavp"] = true,
		["tllca"] = true,
		["tllchover"] = true,
		["tllck"] = true,
		["tllcom"] = true,
		["tllcom3"] = true,
		["tllcom5"] = true,
		["tllcom6"] = true,
		["tllcom7"] = true,
		["tllcs"] = true,
		["tllcsa"] = true,
		["tllcsub"] = true,
		["tllcv"] = true,
		["tllevp"] = true,
		["tllgiant"] = true,
		["tllhevsenan"] = true,
		["tllhp"] = true,
		["tllhpns"] = true,
		["tllhtcb"] = true,
		["tllhtcp"] = true,
		["tlllab"] = true,
		["tllnanotc"] = true,
		["tllnanotc1"] = true,
		["tllnanotc2"] = true,
		["tllplat"] = true,
		["tllsham"] = true,
		["tllsubpen"] = true,
		["tllsy"] = true,
		["tllvp"] = true,
	}
}
	
local Nanos = {
	armnanotc = true,
	armnanotc1 = true,
	armnanotc2 = true,
	armnanotc3 = true,
	cornanotc = true,
	cornanotc1 = true,
	cornanotc2 = true,
	cornanotc3 = true,
	armhevsenan = true,
	corhevsenan = true,
	tllnanotc = true,
	tllnanotc1 = true,
	tllnanotc2 = true,
}

if (Spring.GetModOptions) then
	local modOptions = Spring.GetModOptions()
	for name, ud in pairs(UnitDefs) do  
		if (Commanders[ud.unitname]) then
			ud.energystorage = modOptions.startenergy or 1000
			ud.metalstorage = modOptions.startmetal or 1000
		end
		if (not Commanders[ud.unitname]) then
			ud.mass = math.max(ud.maxdamage / 6.0, ud.buildcostmetal)
		end
	end
end

local WorkerTimeThresholds = { 
	g = {
		{wt = 2000,		color={r = 0.8, g = 1.0, 	b = 0.8}},
		{wt = 1000,		color={r = 0.5, g = 0.9, 	b = 0.5}},
		{wt = 250, 		color={r = 0.2, g = 0.6, 	b = 0.2}},
		{wt = 0, 		color={r = 0.0, g = 0.4, 	b = 0.0}}
	},
	b = {
		{wt = 2000,		color={r = 0.8, g = 1.0, 	b = 1.0}},
		{wt = 1000,		color={r = 0.5, g = 0.85, 	b = 0.85}},
		{wt = 250, 		color={r = 0.2, g = 0.55, 	b = 0.55}},
		{wt = 0, 		color={r = 0.0, g = 0.35, 	b = 0.35}}
	},
	y = {
		{wt = 2000,		color={r = 1.0, g = 1.0, 	b = 0.8}},
		{wt = 1000,		color={r = 0.85, g = 0.85, 	b = 0.5}},
		{wt = 250, 		color={r = 0.55, g = 0.55, 	b = 0.2}},
		{wt = 0, 		color={r = 0.35, g = 0.35, 	b = 0.0}}
	},
	w = {
		{wt = 2000,		color={r = 1.0, g = 1.0, 	b = 1.0}},
		{wt = 1000,		color={r = 0.8, g = 0.8, 	b = 0.8}},
		{wt = 250, 		color={r = 0.5, g = 0.5, 	b = 0.5}},
		{wt = 0, 		color={r = 0.3, g = 0.3, 	b = 0.3}}
	}
}
local NanoCoefs = {
	reclaimCoef = 0.832,
	repairCoef = 0.875
}

function WorkerTimeThresholds:getColor(wt, c)
	local nearestHigherT, nearestLowerT

	for _, v in ipairs(self[c]) do
		if (wt >= v.wt) then
			nearestLowerT = v
			break
		end
		nearestHigherT = v
	end
	
	if not nearestLowerT then 
		nearestLowerT = self[c][#(self[c])]
	end
	
	local rel
	if not nearestHigherT then 
		nearestHigherT = nearestLowerT 
		rel = 0
	else
		rel = (wt - nearestLowerT.wt) / (nearestHigherT.wt -  nearestLowerT.wt)
	end
	
	return 
		(nearestLowerT.color.r + rel * (nearestHigherT.color.r - nearestLowerT.color.r)), 
		(nearestLowerT.color.g + rel * (nearestHigherT.color.g - nearestLowerT.color.g)), 
		(nearestLowerT.color.b + rel * (nearestHigherT.color.b - nearestLowerT.color.b))
end




function compare(a,b)
	
	-- Alphabetically by unit's name
	--ua = UnitDefs[a]
	--ub = UnitDefs[b]
	--return tostring(ua and ua.name) < tostring(ub and ub.name)
	
	return (sortedBuildlistInverted[a] or 0) < (sortedBuildlistInverted[b] or 1)
end

for name, ud in pairs(UnitDefs) do
	if ud.buildoptions then
		table.sort(ud.buildoptions, compare)
	end
end

-- Setting nanocolor
for name, ud in pairs(UnitDefs) do
	if ((ud.workertime or 0) > 0) then
		udwt = ud.workertime
		if(Nanos[ud.unitname]) then
			ud.repairspeed = math.pow(udwt, NanoCoefs.repairCoef)
			ud.reclaimspeed = math.pow(udwt, NanoCoefs.reclaimCoef)
		end
		if(WTimeUnits.tll[ud.unitname]) then
			ud.nanocolor = {WorkerTimeThresholds:getColor(udwt, "y")}
		elseif (WTimeUnits.core[ud.unitname]) then
			ud.nanocolor = {WorkerTimeThresholds:getColor(udwt, "b")}
		elseif (WTimeUnits.arm[ud.unitname]) then
			ud.nanocolor = {WorkerTimeThresholds:getColor(udwt, "g")}
		else
			ud.nanocolor = {WorkerTimeThresholds:getColor(udwt, "w")}
		end
	end
end

-- Setting collisionvolumetest true for all units
for name, ud in pairs(UnitDefs) do
		ud.collisionvolumetest = true
end

