return {
	armcrack = {
		acceleration = 0.108,
		bmcode = 1,
		brakerate = 0.564,
		buildcostenergy = 2950,
		buildcostmetal = 275,
		builder = false,
		buildpic = "armcrack.png",
		buildtime = 2450,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL SMALL MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTSUBNOTSHIP NOTVTOL WEAPON",
		collisionvolumeoffsets = "0 0 -7",
		collisionvolumescales = "34 39 26",
		collisionvolumetype = "box",
		corpse = "DEAD",
		defaultmissiontype = "Standby",
		description = "Rocket Artillery Kbot",
		energymake = 0.6,
		energystorage = 0,
		energyuse = 0.6,
		explodeas = "BIG_UNITEX",
		firestandorders = 1,
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 250,
		losemitheight = 25.12806,
		maneuverleashlength = 640,
		mass = 215,
		maxdamage = 700,
		maxslope = 14,
		maxvelocity = 1.65,
		maxwaterdepth = 21,
		metalstorage = 0,
		mobilestandorders = 1,
		movementclass = "KBOT2",
		name = "Cracker",
		noautofire = false,
		nochasecategory = "VTOL",
		objectname = "ARMCRACK",
		pushresistant = true,
		radaremitheight = 25.12806,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		side = "ARM",
		sightdistance = 310,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 2,
		tedclass = "KBOT",
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.089,
		turnrate = 1103,
		unitname = "armcrack",
		upright = true,
		workertime = 0,
		customparams = {
			buildpic = "armcrack.png",
			requiretech = "Advanced T1 Unit Research Centre",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				damage = 306,
				description = "Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 40,
				hitdensity = 100,
				metal = 52.0085,
				object = "ARMCRACK_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 101,
				description = "Wreckage",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				hitdensity = 100,
				metal = 19.995,
				object = "3X3A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:Arm_Rear_Muzzle",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			lightartmissarm = {
				areaofeffect = 48,
				burst = 8,
				burstrate = 0.15,
				cegtag = "Arm_Trail_rocket",
				craterboost = 0,
				cratermult = 0,
				dance = 10,
				explosiongenerator = "custom:FLASH2",
				firestarter = 20,
				flighttime = 1.5,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "missile",
				name = "Missiles",
				noselfdamage = true,
				range = 700,
				reloadtime = 4,
				smoketrail = true,
				soundhitdry = "xplomed2",
				soundstart = "rockhvy2",
				soundtrigger = true,
				startvelocity = 300,
				texture1 = "null",
				texture2 = "null",
				texture3 = "null",
				texture4 = "null",
				trajectoryheight = 0.1,
				turret = true,
				weaponacceleration = 100,
				weapontimer = 4,
				weapontype = "MissileLauncher",
				weaponvelocity = 600,
				wobble = 1400,
				damage = {
					default = 40,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "Lightartmissarm",
				onlytargetcategory = "NOTVTOL",
			},
		},
	},
}
