return {
	armrottweiler = {
		acceleration = 0.01,
		bmcode = 1,
		brakerate = 0.045,
		buildcostenergy = 5550,
		buildcostmetal = 720,
		builder = false,
		buildtime = 8540,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL MEDIUM MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTSUBNOTSHIP NOTVTOL WEAPON",
		collisionvolumeoffsets = "0 -3 1",
		collisionvolumescales = "37 22 46",
		collisionvolumetest = 1,
		collisionvolumetype = "CylZ",
		corpse = "dead",
		defaultmissiontype = "Standby",
		description = "Medium Combat Riot Tank",
		energymake = 0.8,
		energystorage = 0,
		energyuse = 0.8,
		explodeas = "BIG_TANK",
		firestandorders = 1,
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		maneuverleashlength = 640,
		mass = 754,
		maxdamage = 4520,
		maxslope = 10,
		maxvelocity = 1.5,
		maxwaterdepth = 12,
		metalstorage = 0,
		mobilestandorders = 1,
		movementclass = "TANK3",
		name = "Rottweiler",
		noautofire = false,
		nochasecategory = "SUB VTOL",
		objectname = "ARMROTTWEILER",
		radardistance = 0,
		selfdestructas = "BIG_TANK",
		shootme = 1,
		side = "ARM",
		sightdistance = 355,
		standingfireorder = 2,
		standingmoveorder = 1,
		steeringmode = 1,
		trackoffset = 6,
		trackstrength = 6,
		trackstretch = 1,
		tracktype = "StdTank",
		trackwidth = 34,
		turninplace = 0,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1,
		turnrate = 375,
		unitname = "armrottweiler",
		unitnumber = 6625,
		workertime = 0,
		customparams = {
			requiretech = "Advanced T1 Unit Research Centre",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "arm_corpses",
				damage = 2712,
				description = "Rottweiler Wreckage",
				featuredead = "heap",
				featurereclamate = "smudge01",
				footprintx = 2,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 520,
				object = "armrottweiler_dead",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 1627.20007,
				description = "Rottweiler Heap",
				featurereclamate = "smudge01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 416,
				object = "2x2d",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:Core_Rear_Muzzle",
				[2] = "custom:armrottweiler_mg_flare",
			},
			pieceexplosiongenerators = {
				[1] = "DEBREE5",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
		weapondefs = {
			armrottweiler_cannon = {
				areaofeffect = 96,
				burnblow = true,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.75,
				explosiongenerator = "custom:Explosion_Light_Plasma-2-Orange",
				impulseboost = 0.55,
				impulsefactor = 0.55,
				name = "RiotCannon",
				noselfdamage = true,
				range = 365,
				reloadtime = 2.5,
				rgbcolor = "0.96 0.79 0",
				size = 1.82,
				soundhitdry = "xplosml3",
				soundstart = "canlite3",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 550,
				damage = {
					commanders = 305,
					default = 420,
					subs = 5,
				},
			},
			armrottweiler_missile = {
				areaofeffect = 24,
				burst = 2,
				burstrate = 0.25,
				cegtag = "Arm_Trail_rocket",
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH2",
				firestarter = 70,
				flighttime = 4.5,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "missile",
				name = "Missiles",
				noselfdamage = true,
				range = 605,
				reloadtime = 3,
				smoketrail = true,
				soundhitdry = "xplomed2",
				soundstart = "rockhvy2",
				soundtrigger = true,
				startvelocity = 150,
				texture1 = "null",
				texture2 = "null",
				texture3 = "null",
				texture4 = "null",
				tolerance = 8000,
				tracks = true,
				trajectoryheight = 0.15,
				turnrate = 63000,
				turret = true,
				weaponacceleration = 109,
				weapontimer = 2,
				weapontype = "MissileLauncher",
				weaponvelocity = 280,
				damage = {
					default = 30,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ARMROTTWEILER_CANNON",
				onlytargetcategory = "NOTVTOL",
			},
			[3] = {
				def = "ARMROTTWEILER_MISSILE",
				onlytargetcategory = "NOTVTOL",
			},
		},
	},
}
