return {
	tllhailstorm = {
		acceleration = 0.061,
		brakerate = 0.39,
		buildcostenergy = 210000,
		buildcostmetal = 26250,
		builder = false,
		buildtime = 316305,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = 1,
		category = "ALL HUGE MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTSUBNOTSHIP NOTVTOL WEAPON",
		corpse = "dead",
		description = "Rapid Fire Heavy Kbot",
		designation = "TL-PBT",
		energymake = 20,
		energystorage = 5000,
		energyuse = 20,
		explodeas = "CRAWL_BLAST",
		firestandorders = 1,
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		losemitheight = 38,
		maneuverleashlength = 640,
		mass = 27000,
		maxdamage = 41000,
		maxslope = 14,
		maxvelocity = 1.0,
		maxwaterdepth = 12,
		mobilestandorders = 1,
		movementclass = "VKBOT4",
		name = "Hailstorm",
		noautofire = false,
		nochasecategory = "SUB VTOL",
		objectname = "tllhailstorm",
		radaremitheight = 50,
		selfdestructas = "BANTHA_NUKE",
		side = "TLL",
		sightdistance = 620,
		standingfireorder = 2,
		standingmoveorder = 0,
		steeringmode = 2,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 1.056,
		turnrate = 210,
		unitname = "tllpbot",
		upright = true,
		featuredefs = {
			dead = {
				blocking = true,
				category = "tll_corpses",
				damage = 795.00006,
				description = "Wreckage",
				featuredead = "heap",
				featurereclamate = "smudge01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 216,
				object = "tllpbot_dead",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 477.00003,
				description = "Wreckage",
				featurereclamate = "smudge01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 172.8,
				object = "2x2d",
				reclaimable = true,
				seqnamereclamate = "tree1reclamate",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "tllwarning",
			cant = {
				[1] = "wearoff",
			},
			count = {
				[1] = "tllcount",
				[2] = "tllcount",
				[3] = "tllcount",
				[4] = "tllcount",
				[5] = "tllcount",
				[6] = "tllcount",
			},
			ok = {
				[1] = "tllkbotmove",
			},
			select = {
				[1] = "tllunitok",
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:mediumflare",
			},
		},
		weapondefs = {
			tll_hailstorm = {
				accuracy = 1500,
				areaofeffect = 250,
				cegtag = "Trail_cannon",
				craterboost = 0,
				cratermult = 0,
				energypershot = 4000,
				explosiongenerator = "custom:flash140_fakelight",
				gravityaffected = "TRUE",
				impulseboost = 0,
				impulsefactor = 0,
				metalpershot = 1,
				name = "IntimidatorCannon",
				nogap = 1,
				noselfdamage = true,
				range = 3100,
				reloadtime = 1,
				rgbcolor = "0.71 0.39 0",
				separation = 0.45,
				size = 2.72,
				sizedecay = -0.15,
				soundhitdry = "xplonuk1",
				soundstart = "cannhvy2",
				stages = 20,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 850,
				damage = {
					commanders = 325,
					default = 650,
					experimental_land = 1300,
					experimental_ships = 1300,
					subs = 5,
				},
			},				
		},
		weapons = {
			[1] = {
				def = "TLL_HAILSTORM",
				onlytargetcategory = "NOTVTOL",
			},
		},
	},
}
